# Generated by Django 4.2.3 on 2023-09-11 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entradas', '0005_posteo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntradasBlog',
        ),
        migrations.DeleteModel(
            name='Posteo',
        ),
    ]
