# Generated by Django 4.2.3 on 2023-09-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entradas', '0006_delete_entradasblog_delete_posteo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradasBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('titulo', models.CharField(default='', max_length=40)),
                ('subtitulo', models.CharField(default='', max_length=40)),
                ('contenido', models.CharField(default='', max_length=100)),
                ('usuarioid', models.IntegerField()),
                ('autor', models.CharField(default='', max_length=40)),
                ('imagen', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
