# Generated by Django 4.2.3 on 2023-09-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entradas', '0007_entradasblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='subtitulo',
            field=models.CharField(max_length=150),
        ),
    ]
