# Generated by Django 4.2.3 on 2023-09-13 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0003_alter_mensaje_destinatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='conversacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mensajes.conversacion'),
        ),
    ]
